# CivilServant gratitude
[gratitude]
campaign_tracking = "gratitude_2018"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[gratitude.banners.combi]
filename = "./gratitude/banner_combi.js"
pagename = "B18WMDE_grat_combi"
tracking = "CS18_grat_combi_1"
